# Generated by Django 4.2.27 on 2026-02-04 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('property_sold', 'Property Sold'), ('property_rented', 'Property Rented'), ('property_approved', 'Property Approved'), ('property_rejected', 'Property Rejected'), ('new_request', 'New Property Request'), ('request_status', 'Request Status Changed'), ('request_assigned', 'Request Assigned to Agent'), ('sub_expiring', 'Subscription Expiring Soon'), ('sub_expired', 'Subscription Expired'), ('system', 'System Notification'), ('promo', 'Promotional')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_pushed', models.BooleanField(default=False)),
                ('onesignal_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.property')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.propertyrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx'), models.Index(fields=['user', 'created_at'], name='core_notifi_user_id_7862c3_idx')],
            },
        ),
    ]
