# Generated by Django 4.2.27 on 2026-02-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='listing_credits',
            field=models.PositiveIntegerField(default=0, help_text='Total purchased listing credits'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='used_credits',
            field=models.PositiveIntegerField(default=0, help_text='Credits used for listings'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
