# Generated by Django 4.2.27 on 2026-01-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_phoneotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='code_hash',
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='provider',
            field=models.CharField(default='twilio', max_length=20),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='verification_sid',
            field=models.CharField(db_index=True, default='', help_text='Twilio Verify SID', max_length=100),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('reset', 'Reset Password'), ('login', 'Login')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='phoneotp',
            index=models.Index(fields=['verification_sid'], name='core_phoneo_verific_de8e1f_idx'),
        ),
    ]
