# Generated by Django 4.2.27 on 2026-01-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_phoneotp_code_hash_phoneotp_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='verification_sid',
            field=models.CharField(db_index=True, help_text='Twilio Verify SID', max_length=100),
        ),
    ]
