# Generated by Django 4.2.27 on 2026-01-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='challenge_hash',
            field=models.CharField(db_index=True, default='', max_length=64, unique=True),
        ),
    ]
