# Generated by Django 4.2.27 on 2026-01-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_phoneotp_challenge_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='verification_sid',
            field=models.CharField(db_index=True, help_text='Twilio Verify SID', max_length=100, null=True),
        ),
    ]
