# Generated by Django 4.2.27 on 2026-01-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_amenity_property_area_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='amenities/'),
        ),
    ]
